devops: fix github action

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,7 +21,7 @@ jobs:
       - name: Deploy via SSH
         run: |
           ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
-            cd expediate_web || { echo "Directory expediate_web not found"; exit 1; }
+            cd expediate-web || { echo "Directory expediate_web not found"; exit 1; }
             echo "Inside $(pwd)"
             git pull origin main
             npm install
