chore: fix github action

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,11 +19,12 @@ jobs:
           ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
 
       - name: Deploy via SSH
-        run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
-            cd ${{ secrets.EC2_PATH }}
-            git pull origin main
-            npm i
-            npm run build
-            pm2 restart all || npm run start &
-          EOF
+      run: |
+        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
+          cd expediate_web || { echo "Directory expediate_web not found"; exit 1; }
+          echo "Inside $(pwd)"
+          git pull origin main
+          npm install
+          npm run build
+          pm2 restart all || npm run start &
+        EOF
